package cc.javaee.bbs.model;

public class JifenGroup {
    private Integer id;

    private String name;

    private Integer jifen;

    private String classname;

    private String createtime;

    private String descs;

    private Integer createuserid;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.id
     *
     * @param id the value for jbbs_jifen_group.id
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.name
     *
     * @return the value of jbbs_jifen_group.name
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.name
     *
     * @param name the value for jbbs_jifen_group.name
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.jifen
     *
     * @return the value of jbbs_jifen_group.jifen
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public Integer getJifen() {
        return jifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.jifen
     *
     * @param jifen the value for jbbs_jifen_group.jifen
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setJifen(Integer jifen) {
        this.jifen = jifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.classname
     *
     * @return the value of jbbs_jifen_group.classname
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.classname
     *
     * @param classname the value for jbbs_jifen_group.classname
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.createtime
     *
     * @return the value of jbbs_jifen_group.createtime
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.createtime
     *
     * @param createtime the value for jbbs_jifen_group.createtime
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.descs
     *
     * @return the value of jbbs_jifen_group.descs
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.descs
     *
     * @param descs the value for jbbs_jifen_group.descs
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setDescs(String descs) {
        this.descs = descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_jifen_group.createuserid
     *
     * @return the value of jbbs_jifen_group.createuserid
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_jifen_group.createuserid
     *
     * @param createuserid the value for jbbs_jifen_group.createuserid
     *
     * @mbggenerated Mon May 29 21:11:12 CST 2017
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }
}