package cc.javaee.bbs.model;

/*
 * 用户表
 * 
 */
public class User {
    private Integer id;

    //用户名称
    private String name;

    //登陆名称
    private String loginname;

    //密码
    private String pwd;

    //用户头像
    private String img;

    //邮箱
    private String email;

    //生日
    private String birthday;

    //性别
    private String sex;

    //手机号
    private String mobile;

    //签名
    private String qianming;

    //创建时间
    private String createtime;

    //最后登陆时间
    private String lastlogintime;

    //注册ip
    private String zhuceip;

    //登陆ip
    private String loginip;

    //标识
    private String flag;
    
    //积分
    private Integer jifen;

	//用户组名称
	private String groupname;
	//用户组id
    private Integer groupid;
    
    
    public Integer getJifen() {
		return jifen;
	}

	public void setJifen(Integer jifen) {
		this.jifen = jifen;
	}

	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public Integer getGroupid() {
		return groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.id
     *
     * @param id the value for jbbs_user.id
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.name
     *
     * @return the value of jbbs_user.name
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.name
     *
     * @param name the value for jbbs_user.name
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.loginname
     *
     * @return the value of jbbs_user.loginname
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.loginname
     *
     * @param loginname the value for jbbs_user.loginname
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.pwd
     *
     * @return the value of jbbs_user.pwd
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.pwd
     *
     * @param pwd the value for jbbs_user.pwd
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.img
     *
     * @return the value of jbbs_user.img
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.img
     *
     * @param img the value for jbbs_user.img
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.email
     *
     * @return the value of jbbs_user.email
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.email
     *
     * @param email the value for jbbs_user.email
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.birthday
     *
     * @return the value of jbbs_user.birthday
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.birthday
     *
     * @param birthday the value for jbbs_user.birthday
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.sex
     *
     * @return the value of jbbs_user.sex
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.sex
     *
     * @param sex the value for jbbs_user.sex
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.mobile
     *
     * @return the value of jbbs_user.mobile
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.mobile
     *
     * @param mobile the value for jbbs_user.mobile
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.qianming
     *
     * @return the value of jbbs_user.qianming
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getQianming() {
        return qianming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.qianming
     *
     * @param qianming the value for jbbs_user.qianming
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setQianming(String qianming) {
        this.qianming = qianming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.createtime
     *
     * @return the value of jbbs_user.createtime
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.createtime
     *
     * @param createtime the value for jbbs_user.createtime
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.lastlogintime
     *
     * @return the value of jbbs_user.lastlogintime
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.lastlogintime
     *
     * @param lastlogintime the value for jbbs_user.lastlogintime
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.zhuceip
     *
     * @return the value of jbbs_user.zhuceip
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getZhuceip() {
        return zhuceip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.zhuceip
     *
     * @param zhuceip the value for jbbs_user.zhuceip
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setZhuceip(String zhuceip) {
        this.zhuceip = zhuceip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.loginip
     *
     * @return the value of jbbs_user.loginip
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.loginip
     *
     * @param loginip the value for jbbs_user.loginip
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_user.flag
     *
     * @return the value of jbbs_user.flag
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_user.flag
     *
     * @param flag the value for jbbs_user.flag
     *
     * @mbggenerated Fri May 05 14:00:15 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }
}